version: "3.8"

services:
  shop:
    build: .
    container_name: shop
    depends_on:
      - shop-db
    ports:
      - target: 9091
        published: 9091
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shop-db:5432/products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

  shop-db:
    image: postgres
    container_name: shop-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root